baseURL: "https://azwadriqbal.github.io/"
languageCode: "en"
defaultContentLanguage: "en"
title: "Azwad Iqbal – Population Geneticist & Evolutionary Biologist"

outputs:
  home:
    - HTML
    - RSS
  page:
    - HTML
    - RSS
