baseURL: "https://azwadriqbal.github.io/"
title: "Azwad Iqbal – Population Geneticist & Evolutionary Biologist"

defaultContentLanguage: "en"

outputs:
  home:
    - HTML
    - RSS
    - headers
    - redirects
    - backlinks
  section:
    - HTML
    - RSS