hugoblox:
  schema: "2.0"
  identity:
    name: "Azwad Iqbal"
    tagline: "Population geneticist & evolutionary biologist"
    description: "Population genomics | Invasive species evolution | Conservation | PhD @ Cornell"
    type: person
    social:
      twitter: azwadiqbal
      github: azwadriqbal
      orcid: "0000-0002-8266-7284"
      scholar: "tTnoDp0AAAAJ"
  theme:
    mode: dark
    pack: retro
  layout:
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: false
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: false
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: false
  search:
    enable: true
