baseURL: https://azwadriqbal.github.io
languageCode: en-us
title: Azwad Iqbal
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
#   main:
    # - identifier: research
    #   name: Research
    #   title: Research projects
    #   url: /research
    #   weight: 1
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Azwad Iqbal"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/shad_icon.svg"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
      disableThemeToggle: true
      defaultTheme: "dark"

  font:
    fontSize: 1.25rem # default: 1rem
    fontWeight: 500 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  color:
    textColor: "#343a40"
    secondaryTextColor: "#6c757d"
    textLinkColor: "#2e6f40"
    backgroundColor: "#eaedf0"
    secondaryBackgroundColor: "#64ffda1a"
    primaryColor: "#2e6f40"
    secondaryColor: "#f8f9fa"

    darkmode:
      textColor: "#e4e6eb"
      secondaryTextColor: "#b0b3b8"
      textLinkColor: "#B6CBEF"
      backgroundColor: "#10151A"
      secondaryBackgroundColor: "#212529"
      primaryColor: "#c6d4ec"
      secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "images/shad_icon.svg" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Azwad Iqbal" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: true
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, I'm"
    title: "Azwad Iqbal"
    subtitle: "I'm a population geneticist & evolutionary biologist"
    content: "I'm interesting in using population genomics to study rapid evolution in invasive species. My research uses a combination of molecular and analytical methods to reconstruct the evolutionary histories of biological invasions."
    image: /images/azwad.jpg
    image_second: /images/shad_2.jpg
    bottomImage: 
      enable: true
    roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "CV"
      url: "https://raw.githubusercontent.com/azwadriqbal/azwadriqbal.github.io/refs/heads/main/cv/iqbal_azwad_cv_11_04_24.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/azwadriqbal
        - icon: fab fa-x-twitter
          url: https://x.com/azwadiqbal


  # About
  about:
    enable: true
    title: "About"
    image: "/images/me_2.jpg"
    content: |-
      I am a broadly trained **population geneticist** and **evolutionary biologist** with a background in molecular ecology. I've worked with [large mammalian herbivores](https://www.pnas.org/doi/10.1073/pnas.2204400119) in African savannas, [yellow-fever mosquitoes](https://www.nature.com/articles/s41586-022-04675-4), and am currently working with America's "[Founding Fish](https://us.macmillan.com/books/9780374528836/thefoundingfish)", the American shad (*Alosa sapidissima*), as part of my dissertation in the [Therkildsen Lab](https://www.therkildsenlab.org/) at Cornell University.

      I am passionate about leveraging genomics to inform conservation and have actively collaborated with stakeholders in developing my research.

      Outside of my research, I enjoy powerlifting, playing video games, listening to music (mostly hip hop along with some indie and electronic), and [producing music](https://soundcloud.com/wadzmix) (in the form of mixes for competitive bhangra teams) 


    skills:
      enable: true
      title: "I am experienced with a variety of programming languages and laboratory techniques, including:"
      items:
        - "R"
        - "Python"
        - "Bash"
        - "Snakemake"
        - "Whole-genome sequencing"
        - "[Haplotagging](https://www.pnas.org/doi/suppl/10.1073/pnas.2015005118)"

  # projects
  projects:
    enable: true
    title: "Research"
    items:
      - title: Adaptive Genomics of Invasive American shad
        content: |-
          The bulk of my dissertation is focused on identifying genomic signals of rapid adaptation in invasive populations of American shad. I'm especially interested in studying how structural variants, standing variation, and demographic changes have shaped the evolution of invasive populations.
        image: /images/inversion_gradient.png
        badges:
          - "Invasion Genomics"
          - "Rapid Evolution"

      - title: Haplotype-tagging ("Haplotagging")
        content: I am collaborating with the Genomics Innovation Hub at Cornell to further develop Haplotagging - a linked-read sequencing technology designed to generate population-scale sequencing data while retaining haplotype information in non-model species. Click the GitHub icon to learn more about our analytical pipeline, Harpy.
        image: /images/haplo_beads.png
        featured:
          name: Haplotagging Website
          link: https://www.fml.tuebingen.mpg.de/9418/haplotaggingheli
        badges:
          - "Linked-read sequencing"
          - "Haplotypes"
        links:
          - icon: fab fa-github
            url: https://github.com/pdimens/harpy

      - title: Museomics of Invasive shad
        content: I am working with a variety of museums to leverage historical tissue samples of American shad to study the how standing variation and population bottlenecks may have affected the tempo and trajectory of evolutionary change in invasive lineages. 
        image: /images/old_shad.jpg
        badges:
          - "Historical DNA"
          - "Demographic inference"
          - "Standing Variation"


  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "PhD Candidate"
        company: "Therkildsen Lab - Cornell University"
        companyUrl: "https://therkildsenlab.org"
        date: "Aug 2021 - present"
        featuredLink:
          enable: true
          name: "Therkildsen Lab Website"
          url: "https://therkildsenlab.org"
        info:
          enable: false          
        content: |
          I am PhD Candidate at Cornell University in the department of Natural Resources and the Environment. I am currently working on several projects, including:
        
          - Studying the rapid evolution of invasive American shad with whole-genome resequencing
          - Developing "Haplotagging" linked-read sequencing technology for non-model organisms
          - Leveraging museum collections to study the role of standing genetic variation in invasion success

      - job: "Research Specialist"
        company: "McBride Lab - Princeton University"
        companyUrl: "https://mcbridelab.princeton.edu/"
        date: "Sep 2019 - Jul 2021"
        featuredLink:
          enable: true
          name: "Co-Authored Publication"
          url: "https://www.nature.com/articles/s41586-022-04675-4"
        info:
          enable: false
          content: I worked as a software developer for more than one year in Amazon.
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Lead backend developer for a product.
          - Created a frontend design for a product.

      - job: "Undergraduate Researcher"
        company: "Pringle Lab - Princeton University"
        companyUrl: "https://pringle.princeton.edu"
        date: "Jul 2016 - Jun 2019"
        info:
          enable: false
        featuredLink:
          enable: true
          name: "Co-Authored Publication"
          url: "https://www.pnas.org/doi/10.1073/pnas.2204400119"
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Lead backend developer for a product.
          - Created a frontend design for a product.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "PhD in Natural Resources and the Environment"
        school:
          name: "Cornell University"
          url: "https://cornell.edu"
        date: "2021 - 2026"
        GPA: "4.0"
        content: |-
            - NSF Graduate Research Fellow
            - Society for the Study of Evolution (SSE) R.C. Lewontin Award
            - Cornell Center for Vertebrate Genomics Scholar

      - title: "Bachelor of Arts in Ecology and Evolutionary Biology"
        school:
          name: "Princeton University"
          url: "https://princeton.edu"
        date: "2015 - 2019"
        GPA: "3.85 out of 4.0"
        content: |-
            - *Summa cum laude*
            - Sigma Xi Book Award for Outstanding Research
            - Senior Thesis Prize in Ecology

  # Achievements
  achievements:
    enable: false
    title: "Honors"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: /images/achievment.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: /images/achievment.jpg
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
        image: /images/achievment.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com



  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: Shoot me an email!
    btnName: Mail me
    btnLink: mailto:ari22@cornell.edu
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/azwadriqbal
      linkedin: https://www.linkedin.com/in/azwad-iqbal-689252127/
      twitter: https://twitter.com/azwadiqbal

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>